class Soal12_MyException extends Exception{
    private String Teks;
    Soal12_MyException(String s){// step 2.2 (amir) benar, ini dijalankan 
        Teks="Exception generated by: "+s;//output step 2.1 (amir) ini: Exception generated by: amir
        System.out.println(Teks);
    }
}

class Eksepsi{  
    static void tampil(String s)throws Exception{
        System.out.println("Tampil");// ini dahulu yg yg di eksekusi step 1 (ali) //Program kembali masuk ke metode tampil, sekarang dengan s = "amir" step 1 (amir)
        if(s.equals("amir")){// step 2.1 (ali) Pengecekan kondisi if (s.equals("amir")). 
        // Karena "ali" tidak sama dengan "amir", blok if diabaikan (tidak ada exception yang dilempar).
        // step 2.1 (amir). if (s.equals("amir")). Karena benar, perintah throw new Soal12_MyException("amir") dijalankan.
            throw new Soal12_MyException(s);
        }
        System.out.println("OK!");// output step 2.1(ali)
    }
    public static void main(String[] args)throws Exception{
        try{
            tampil("ali");// "ali" dahulu di step 2.2(ali)
            tampil("amir");
        }
        catch(Soal12_MyException ex){// step 3 (amir). ini terkahir di eksekusi
            System.out.println("Tangkap:"+ex);
        }
    }
}

/* output
PS C:\TUGASKULIAH\semester4\tugas10> java Eksepsi
Tampil
OK!
Tampil
Exception generated by: amir
Tangkap:Soal12_MyException */